### PR TITLE
Vscode task relative path error

### PR DESCRIPTION
**Pull request by YouriMulder**
Relative path execution gave the following error:

> Executing task: ../../../programs/bmptk/tools/bmptk-make.exe <
'..' is not recognized as an internal or external command,
operable program or batch file.
The terminal process terminated with exit code: 1

Because bmptk-make.exe is in the path we can execute without using a relative path.

### CODE REVIEW

**Comment by YouriMulder** [comment]
Another solution could be using quotes: "../../../programs/bmptk/tools/bmptk-make.exe"

**Comment by itzandroidtab** [comment]
If the extra quotes work that will probably be the better solution

**Comment by itzandroidtab** [comment]
I have made a branch for the hotfix with escaped quotes added to the commands. Could you try if they work? [branch](https://github.com/R2D2-2019/R2D2-build/tree/task_hotfix_cmd)

**Comment by itzandroidtab** [comment]
This is fixed in #6 so im closing this one

**Pull request closed without merging**
